### ISSUE TITLE
Bnvib files? 

### ISSUE THREAD

**Issue by cualquiercosa327** [Amethyst-Sysadmin/Howl#1]
Hi, I would suggest to add this file format used on Nintendo Switch games,
the famous "HD rumble".
They can make "feel" things as balls moving...
The format is fully RE and documented.
They are lots of ways to extract them but the easiest is using yuzu
(although Nintendo made it were no develop anymore, you can find it easily including the src
and it has the option to logs the frecuency/Amplityde the joycon would play.
Advice : try it with 1 2 Switch and kazuaze (balls counting) mini game.
Thanks

**Comment by Amethyst-Sysadmin** [comment]
Thanks for the suggestion! I've never had a Switch, so it's not really a format I'm interested in adding direct support for.

If somebody wanted to work on this, I think the best way to do it would be to make a converter that translates them into HWL files for the app to play. Similar to the Python script that converts audio files to HWL format, but probably less complicated as it could figure out the frequency/amplitude from the files so wouldn't have to run pitch detection like we do for audio files.

If converted in that way, they would be playable without any specific support being needed in the app.
